# Generated by Django 5.2.17 on 2026-09-20 20:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('fiscal_id', models.CharField(blank=True, max_length=40)),
                ('ice', models.CharField(blank=True, max_length=15)),
                ('demo', models.BooleanField(default=False)),
                ('next_sale_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company_limit', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_org_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur société'), ('commercial', 'Commercial'), ('accountant', 'Comptable'), ('supervisor', 'Superviseur'), ('viewer', 'Lecture seule')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=30)),
                ('result', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.organization'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=60)),
                ('cost', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('minimum', models.PositiveIntegerField(default=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('request_key', models.CharField(max_length=80)),
                ('customer_name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField()),
                ('subtotal', models.PositiveBigIntegerField()),
                ('tax_bps', models.PositiveIntegerField(default=0)),
                ('tax', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('paid', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=12)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('method', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.product')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('cost', models.PositiveBigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='customer_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_company_membership'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'commercial', 'accountant', 'supervisor', 'viewer'])), name='valid_membership_role'),
        ),
        migrations.AddConstraint(
            model_name='operationrequest',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_company_operation'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), models.F('company'), name='unique_company_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='product_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'request_key'), name='unique_company_sale_request'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_sale_number'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='sale_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('paid__lte', models.F('total'))), name='sale_not_overpaid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'cancelled'])), name='valid_sale_status'),
        ),
    ]
