# Generated by Django 5.2.17 on 2026-09-20 21:13

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_company_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next_purchase_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('supplier_name', models.CharField(max_length=160)),
                ('supplier_reference', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subtotal', models.PositiveBigIntegerField()),
                ('tax', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('paid', models.PositiveBigIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.purchase'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('fiscal_id', models.CharField(blank=True, max_length=40)),
                ('ice', models.CharField(blank=True, max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('method', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('tax_bps', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveBigIntegerField()),
                ('tax', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.purchase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_positive_quantity'), models.CheckConstraint(condition=models.Q(('tax_bps__lte', 10000)), name='purchase_tax_limit')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='supplier_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='purchase_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_purchase_number'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('supplier_reference'), models.F('supplier'), models.F('company'), name='unique_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'received', 'cancelled'])), name='valid_purchase_status'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('paid__lte', models.F('total'))), name='purchase_not_overpaid'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'received'), ('paid', 0), _connector='OR'), name='only_received_purchase_paid'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_positive'),
        ),
    ]
