# Generated by Django 5.2.17 on 2026-09-20 21:13

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('tax')))), name='purchase_total_matches'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('invoice_date')), _connector='OR'), name='purchase_due_date_order'),
        ),
    ]
