# Generated by Django 5.2.17 on 2026-09-22 11:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_purchase_company_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='draft', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.PositiveIntegerField(null=True)),
                ('journal_code', models.CharField(blank=True, max_length=12)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.journal')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.accountingperiod')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.purchase')),
                ('reversal_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.journalentry')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.sale')),
            ],
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=160)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('debit', models.PositiveBigIntegerField(default=0)),
                ('credit', models.PositiveBigIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.journalentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('company'), name='unique_company_account'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='account_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='period_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='period_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('company'), name='unique_company_journal'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='journal_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='entry_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('journal', 'number'), name='unique_journal_entry_number'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discarded'), _negated=True), fields=('company', 'sale'), name='one_sale_transfer'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discarded'), _negated=True), fields=('company', 'purchase'), name='one_purchase_transfer'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discarded'), _negated=True), fields=('reversal_of',), name='one_entry_reversal'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'posted', 'discarded'])), name='valid_entry_status'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('sale__isnull', True), ('purchase__isnull', True), _connector='OR'), name='one_invoice_source'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('reversal_of__isnull', True), models.Q(('sale__isnull', True), ('purchase__isnull', True)), _connector='OR'), name='reversal_without_source'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('number__isnull', False), ('posted_at__isnull', False), ('posted_by__isnull', False), ('status', 'posted')), models.Q(models.Q(('status', 'posted'), _negated=True), ('number__isnull', True), ('posted_at__isnull', True), ('posted_by__isnull', True)), _connector='OR'), name='entry_posting_metadata'),
        ),
        migrations.AddConstraint(
            model_name='entryline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='line_one_positive_side'),
        ),
    ]
