# Generated by Django 5.2.17 on 2026-09-22 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_accounting_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='one_invoice_source',
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='reversal_without_source',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='customer_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.payment'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='settlement_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_entries', to='workspace.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='supplier_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.supplierpayment'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_payment__isnull', True), ('purchase__isnull', True), ('sale__isnull', True)), models.Q(('purchase__isnull', True), ('sale__isnull', True), ('supplier_payment__isnull', True)), models.Q(('customer_payment__isnull', True), ('sale__isnull', True), ('supplier_payment__isnull', True)), models.Q(('customer_payment__isnull', True), ('purchase__isnull', True), ('supplier_payment__isnull', True)), _connector='OR'), name='one_accounting_source'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_payment__isnull', True), ('settlement_invoice__isnull', True), ('supplier_payment__isnull', True)), models.Q(('settlement_invoice__isnull', False), models.Q(('customer_payment__isnull', False), ('supplier_payment__isnull', False), _connector='OR')), _connector='OR'), name='payment_invoice_required'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('reversal_of__isnull', True), models.Q(('customer_payment__isnull', True), ('purchase__isnull', True), ('sale__isnull', True), ('supplier_payment__isnull', True)), _connector='OR'), name='reversal_without_source'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='payment_company_pair'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(fields=('id', 'company'), name='supplierpayment_company_pair'),
        ),
        migrations.AddField(
            model_name='settlementmatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company'),
        ),
        migrations.AddField(
            model_name='settlementmatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementmatch',
            name='invoice_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_matches', to='workspace.journalentry'),
        ),
        migrations.AddField(
            model_name='settlementmatch',
            name='payment_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_matches', to='workspace.journalentry'),
        ),
        migrations.AddField(
            model_name='settlementmatch',
            name='voided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='settlementmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('payment_entry',), name='one_active_payment_match'),
        ),
        migrations.AddConstraint(
            model_name='settlementmatch',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_match_positive'),
        ),
        migrations.AddConstraint(
            model_name='settlementmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='match_void_metadata'),
        ),
    ]
