# Generated by Django 5.2.17 on 2026-09-22 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_settlement_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cadence', models.CharField(max_length=10)),
                ('sales_basis', models.CharField(max_length=10)),
                ('purchase_basis', models.CharField(max_length=10)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('lines', models.JSONField(default=list)),
                ('opening_credit', models.PositiveBigIntegerField(default=0)),
                ('credit_note', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('company_snapshot', models.JSONField(default=dict)),
                ('approved_snapshot', models.JSONField(default=dict)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('voided_at', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'voided', 'discarded'])), name='vat_valid_status'), models.CheckConstraint(condition=models.Q(('cadence__in', ['monthly', 'quarterly'])), name='vat_valid_cadence'), models.CheckConstraint(condition=models.Q(('sales_basis__in', ['invoices', 'payments']), ('purchase_basis__in', ['invoices', 'payments'])), name='vat_valid_basis'), models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='vat_date_order'), models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('checksum', ''), ('status__in', ['draft', 'discarded'])), models.Q(('status__in', ['approved', 'voided']), ('approved_at__isnull', False), ('approved_by__isnull', False), models.Q(('checksum', ''), _negated=True)), _connector='OR'), name='vat_approval_metadata'), models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status__in', ['voided', 'discarded']), _negated=True), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('status__in', ['voided', 'discarded']), ('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='vat_void_metadata')],
            },
        ),
    ]
