'use strict';
Object.assign(AtlasAccounting, {
  settlementsView(){
    const rows=this.data().reconciliation,can=this.can();
    const paymentRows=rows.flatMap(r=>r.payments),waiting=paymentRows.filter(p=>p.status!=='posted'),unmatched=paymentRows.filter(p=>p.status==='posted'&&!p.match_id);
    return `<div class="notice">Transférez les règlements, vérifiez leurs écritures, puis lettrez-les avec leur facture. Le lettrage associe les écritures sans modifier les paiements commerciaux. Vue cumulée, toutes périodes confondues.</div><div class="toolbar"><p class="stat-note">${waiting.length} règlements à comptabiliser · ${unmatched.length} à lettrer</p>${AtlasPlatform.can('export')?`<a class="btn" href="/api/companies/${AtlasPlatform.companyId}/accounting/reconciliation-export">Exporter le suivi</a>`:''}</div>${rows.length?rows.map(r=>{
      const e=this.data().entries.find(e=>e.id===r.invoice_entry_id),fully=r.available&&r.matched===r.total&&r.payment_gap===0;
      return `<section class="card settlement-card" data-settlement-invoice="${r.kind}-${r.id}"><div class="card-head"><div><h2>${esc(r.number)} · ${esc(r.party)}</h2><p class="stat-note">${r.kind==='sale'?'Client':'Fournisseur'} · ${currency(r.total)} TTC</p></div>${badge(fully?'Lettrée':r.matched?'Partiellement lettrée':'À rapprocher',fully?'':'warning')}${e?this.button('view',this.code(e),e.id):''}</div><div class="settlement-summary"><div><small>Payé au commercial</small><strong>${currency(r.paid)}</strong></div><div><small>Règlements comptabilisés</small><strong>${currency(r.posted_payments)}</strong></div><div><small>Montant lettré</small><strong>${currency(r.matched)}</strong></div><div><small>Reste comptable</small><strong>${r.accounting_remaining===null?'—':currency(r.accounting_remaining)}</strong></div></div>${r.payment_gap?`<p class="settlement-note">Écart commercial / comptabilité : <strong>${currency(r.payment_gap)}</strong>. Vérifiez les règlements restant à comptabiliser.</p>`:''}${!r.available?'<p class="settlement-note">La facture doit être comptabilisée, sans contrepassation en cours, pour transférer et lettrer ses règlements.</p>':''}${r.payments.length?`<div class="table-scroll"><table><thead><tr><th>Règlement</th><th class="amount">Montant</th><th>Comptabilité</th><th>Lettrage</th><th>Actions</th></tr></thead><tbody>${r.payments.map(p=>{
        const pe=this.data().entries.find(e=>e.id===p.entry_id);
        return `<tr data-settlement-payment="${p.kind}-${p.id}"><td>${date(p.date+'T12:00:00')}<small class="purchase-sub">${esc(p.method)} ${esc(p.reference)}</small></td><td class="amount">${currency(p.amount)}</td><td>${pe?this.status(pe):badge('À transférer','neutral')}${p.reversal_pending?'<small class="purchase-sub">Contrepassation en cours</small>':''}</td><td>${p.match_id?badge(`Lettré · L-${p.match_id}`):badge('Non lettré','neutral')}</td><td><div class="settlement-actions">${pe?this.button('view',this.code(pe),pe.id):can&&r.available?`<button class="btn" data-action="accounting-payment-transfer" data-kind="${p.kind}" data-id="${p.id}">Transférer le règlement</button>`:''}${can&&p.match_id?this.button('unmatch','Délettrer',p.match_id):can&&r.available&&pe?.status==='posted'&&!p.reversal_pending?this.button('match','Lettrer',pe.id):''}</div></td></tr>`;
      }).join('')}</tbody></table></div>`:'<p class="settlement-note">Aucun règlement enregistré sur cette facture.</p>'}</section>`;
    }).join(''):empty('Aucune facture à rapprocher','Les factures clients et les achats réceptionnés apparaîtront ici.')}<p class="table-count">Ce suivi concerne les règlements transférés depuis Atlas. Les écritures manuelles ne sont pas associées automatiquement. Le rapprochement avec un relevé bancaire sera traité séparément.</p>`;
  },
  paymentTransferModal(kind,id){
    if(!this.ready())return;
    const row=this.data().reconciliation.find(r=>r.payments.some(p=>p.kind===kind&&p.id===id));
    const payment=row.payments.find(p=>p.kind===kind&&p.id===id),invoice=this.data().entries.find(e=>e.id===row.invoice_entry_id);
    const counter=this.data().lines.find(l=>l.entry_id===invoice.id&&(kind==='customer_payment'?l.debit>0:l.credit>0));
    const accounts=this.data().accounts.filter(a=>a.active&&a.id!==counter.account_id);
    const sourceDate=payment.date<invoice.date?invoice.date:payment.date,period=this.data().periods.find(p=>!p.closed&&p.start<=sourceDate&&p.end>=sourceDate);
    modal('Transférer un règlement',`${row.number} · ${row.party}`,`<input type="hidden" name="kind" value="${kind}"><input type="hidden" name="source_id" value="${id}"><div class="notice">${currency(payment.amount)} · ${esc(payment.method)} · ${date(payment.date+'T12:00:00')}<br>Compte de tiers repris de la facture : ${esc(counter.account_code)} · ${esc(counter.account_name)}.</div><div class="form-grid">${this.contextFields({period_id:period?.id,date:period?sourceDate:undefined},false)}${this.select('Compte de banque ou caisse','cash_account_id',accounts)}</div><div class="notice">Choisissez le compte correspondant au règlement. Vérifiez qu’il n’a pas déjà été comptabilisé par une écriture manuelle.</div>`,`${cancelButton}<button class="btn primary" type="submit">Créer le brouillon du règlement</button>`,true,'accounting-payment-transfer-form');this.key=crypto.randomUUID();
  },
  matchModal(id){
    const e=this.data().entries.find(e=>e.id===id),s=e.source_snapshot;
    modal('Lettrer ce règlement',`${this.code(e)} · ${s.invoice_reference}`,`<input type="hidden" name="payment_entry_id" value="${id}"><div class="notice">Associer ${currency(s.total)} à la facture ${esc(s.invoice_reference)} de ${esc(s.party)}. Une facture peut être lettrée avec plusieurs règlements partiels.</div>`,`${cancelButton}<button class="btn primary" type="submit">Confirmer le lettrage</button>`,false,'accounting-match-form');this.key=crypto.randomUUID();
  },
  unmatchModal(id){
    const m=this.data().matches.find(m=>m.id===id);
    modal('Délettrer ce règlement',`Lettrage L-${id} · ${currency(m.amount)}`,`<input type="hidden" name="id" value="${id}"><div class="notice">Les écritures et le règlement commercial sont conservés. Le motif restera dans l’historique.</div>${field('Motif','reason','','text',true,true)}`,`${cancelButton}<button class="btn primary" type="submit">Confirmer le délettrage</button>`,false,'accounting-unmatch-form');this.key=crypto.randomUUID();
  }
});
